/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Driver = IDL.Record({
  'id' : IDL.Text,
  'assignedTruckId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'licenseNumber' : IDL.Text,
  'salaryUSD' : IDL.Float64,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const FinanceEntry = IDL.Record({
  'id' : IDL.Text,
  'entryType' : IDL.Text,
  'relatedTripId' : IDL.Opt(IDL.Text),
  'date' : Time,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amountUSD' : IDL.Float64,
});
export const MaintenanceRecord = IDL.Record({
  'id' : IDL.Text,
  'kmAtService' : IDL.Nat,
  'serviceDate' : Time,
  'truckId' : IDL.Text,
  'serviceType' : IDL.Text,
  'mechanicName' : IDL.Text,
  'costUSD' : IDL.Float64,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'notificationType' : IDL.Text,
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'cargoType' : IDL.Text,
  'assignedTruckId' : IDL.Opt(IDL.Text),
  'customerPhone' : IDL.Text,
  'createdAt' : Time,
  'assignedDriverId' : IDL.Opt(IDL.Text),
  'deliveryLocation' : IDL.Text,
  'priceUSD' : IDL.Float64,
  'pickupLocation' : IDL.Text,
});
export const Trip = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'truckId' : IDL.Text,
  'driverId' : IDL.Text,
  'destination' : IDL.Text,
  'cargoType' : IDL.Text,
  'endDate' : IDL.Opt(Time),
  'createdAt' : Time,
  'fuelCostUSD' : IDL.Float64,
  'orderId' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'startLocation' : IDL.Text,
  'tripPriceUSD' : IDL.Float64,
  'startDate' : Time,
});
export const Truck = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'model' : IDL.Text,
  'currentKm' : IDL.Nat,
  'assignedDriverId' : IDL.Opt(IDL.Text),
  'plateNumber' : IDL.Text,
  'lastServiceDate' : Time,
  'capacityTons' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MonthlyReport = IDL.Record({
  'totalIncome' : IDL.Float64,
  'totalExpenses' : IDL.Float64,
  'profit' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const DashboardStats = IDL.Record({
  'pendingOrders' : IDL.Nat,
  'trucksOnTrip' : IDL.Nat,
  'availableTrucks' : IDL.Nat,
  'trucksInMaintenance' : IDL.Nat,
  'monthlyExpenses' : IDL.Float64,
  'monthlyIncome' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Settings = IDL.Record({
  'motto' : IDL.Text,
  'language' : IDL.Text,
  'logoUrl' : IDL.Opt(ExternalBlob),
  'companyName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDriver' : IDL.Func([Driver], [], []),
  'addFinanceEntry' : IDL.Func([FinanceEntry], [], []),
  'addMaintenanceRecord' : IDL.Func([MaintenanceRecord], [], []),
  'addNotification' : IDL.Func([Notification], [], []),
  'addOrder' : IDL.Func([Order], [], []),
  'addTrip' : IDL.Func([Trip], [], []),
  'addTruck' : IDL.Func([Truck], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDriver' : IDL.Func([IDL.Text], [], []),
  'deleteFinanceEntry' : IDL.Func([IDL.Text], [], []),
  'deleteMaintenanceRecord' : IDL.Func([IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Text], [], []),
  'deleteTrip' : IDL.Func([IDL.Text], [], []),
  'deleteTruck' : IDL.Func([IDL.Text], [], []),
  'getAnnualReport' : IDL.Func([IDL.Nat], [MonthlyReport], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDriver' : IDL.Func([IDL.Text], [Driver], ['query']),
  'getFinanceEntry' : IDL.Func([IDL.Text], [FinanceEntry], ['query']),
  'getMaintenanceRecord' : IDL.Func([IDL.Text], [MaintenanceRecord], ['query']),
  'getMonthlyReport' : IDL.Func([IDL.Nat, IDL.Nat], [MonthlyReport], ['query']),
  'getNotification' : IDL.Func([IDL.Text], [Notification], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getTrip' : IDL.Func([IDL.Text], [Trip], ['query']),
  'getTruck' : IDL.Func([IDL.Text], [Truck], ['query']),
  'getTrucksNeedingMaintenance' : IDL.Func([], [IDL.Vec(Truck)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'listFinanceEntries' : IDL.Func([], [IDL.Vec(FinanceEntry)], ['query']),
  'listMaintenanceByTruck' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MaintenanceRecord)],
      ['query'],
    ),
  'listMaintenanceRecords' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceRecord)],
      ['query'],
    ),
  'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'listTrucks' : IDL.Func([], [IDL.Vec(Truck)], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDriver' : IDL.Func([IDL.Text, Driver], [Driver], []),
  'updateFinanceEntry' : IDL.Func([IDL.Text, FinanceEntry], [FinanceEntry], []),
  'updateMaintenanceRecord' : IDL.Func(
      [IDL.Text, MaintenanceRecord],
      [MaintenanceRecord],
      [],
    ),
  'updateOrder' : IDL.Func([IDL.Text, Order], [Order], []),
  'updateSettings' : IDL.Func([Settings], [], []),
  'updateTrip' : IDL.Func([IDL.Text, Trip], [Trip], []),
  'updateTruck' : IDL.Func([IDL.Text, Truck], [Truck], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Driver = IDL.Record({
    'id' : IDL.Text,
    'assignedTruckId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'licenseNumber' : IDL.Text,
    'salaryUSD' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const FinanceEntry = IDL.Record({
    'id' : IDL.Text,
    'entryType' : IDL.Text,
    'relatedTripId' : IDL.Opt(IDL.Text),
    'date' : Time,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amountUSD' : IDL.Float64,
  });
  const MaintenanceRecord = IDL.Record({
    'id' : IDL.Text,
    'kmAtService' : IDL.Nat,
    'serviceDate' : Time,
    'truckId' : IDL.Text,
    'serviceType' : IDL.Text,
    'mechanicName' : IDL.Text,
    'costUSD' : IDL.Float64,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'notificationType' : IDL.Text,
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'cargoType' : IDL.Text,
    'assignedTruckId' : IDL.Opt(IDL.Text),
    'customerPhone' : IDL.Text,
    'createdAt' : Time,
    'assignedDriverId' : IDL.Opt(IDL.Text),
    'deliveryLocation' : IDL.Text,
    'priceUSD' : IDL.Float64,
    'pickupLocation' : IDL.Text,
  });
  const Trip = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'truckId' : IDL.Text,
    'driverId' : IDL.Text,
    'destination' : IDL.Text,
    'cargoType' : IDL.Text,
    'endDate' : IDL.Opt(Time),
    'createdAt' : Time,
    'fuelCostUSD' : IDL.Float64,
    'orderId' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'startLocation' : IDL.Text,
    'tripPriceUSD' : IDL.Float64,
    'startDate' : Time,
  });
  const Truck = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'model' : IDL.Text,
    'currentKm' : IDL.Nat,
    'assignedDriverId' : IDL.Opt(IDL.Text),
    'plateNumber' : IDL.Text,
    'lastServiceDate' : Time,
    'capacityTons' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MonthlyReport = IDL.Record({
    'totalIncome' : IDL.Float64,
    'totalExpenses' : IDL.Float64,
    'profit' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const DashboardStats = IDL.Record({
    'pendingOrders' : IDL.Nat,
    'trucksOnTrip' : IDL.Nat,
    'availableTrucks' : IDL.Nat,
    'trucksInMaintenance' : IDL.Nat,
    'monthlyExpenses' : IDL.Float64,
    'monthlyIncome' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Settings = IDL.Record({
    'motto' : IDL.Text,
    'language' : IDL.Text,
    'logoUrl' : IDL.Opt(ExternalBlob),
    'companyName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDriver' : IDL.Func([Driver], [], []),
    'addFinanceEntry' : IDL.Func([FinanceEntry], [], []),
    'addMaintenanceRecord' : IDL.Func([MaintenanceRecord], [], []),
    'addNotification' : IDL.Func([Notification], [], []),
    'addOrder' : IDL.Func([Order], [], []),
    'addTrip' : IDL.Func([Trip], [], []),
    'addTruck' : IDL.Func([Truck], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDriver' : IDL.Func([IDL.Text], [], []),
    'deleteFinanceEntry' : IDL.Func([IDL.Text], [], []),
    'deleteMaintenanceRecord' : IDL.Func([IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Text], [], []),
    'deleteTrip' : IDL.Func([IDL.Text], [], []),
    'deleteTruck' : IDL.Func([IDL.Text], [], []),
    'getAnnualReport' : IDL.Func([IDL.Nat], [MonthlyReport], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDriver' : IDL.Func([IDL.Text], [Driver], ['query']),
    'getFinanceEntry' : IDL.Func([IDL.Text], [FinanceEntry], ['query']),
    'getMaintenanceRecord' : IDL.Func(
        [IDL.Text],
        [MaintenanceRecord],
        ['query'],
      ),
    'getMonthlyReport' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlyReport],
        ['query'],
      ),
    'getNotification' : IDL.Func([IDL.Text], [Notification], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getTrip' : IDL.Func([IDL.Text], [Trip], ['query']),
    'getTruck' : IDL.Func([IDL.Text], [Truck], ['query']),
    'getTrucksNeedingMaintenance' : IDL.Func([], [IDL.Vec(Truck)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'listFinanceEntries' : IDL.Func([], [IDL.Vec(FinanceEntry)], ['query']),
    'listMaintenanceByTruck' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MaintenanceRecord)],
        ['query'],
      ),
    'listMaintenanceRecords' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceRecord)],
        ['query'],
      ),
    'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'listTrucks' : IDL.Func([], [IDL.Vec(Truck)], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDriver' : IDL.Func([IDL.Text, Driver], [Driver], []),
    'updateFinanceEntry' : IDL.Func(
        [IDL.Text, FinanceEntry],
        [FinanceEntry],
        [],
      ),
    'updateMaintenanceRecord' : IDL.Func(
        [IDL.Text, MaintenanceRecord],
        [MaintenanceRecord],
        [],
      ),
    'updateOrder' : IDL.Func([IDL.Text, Order], [Order], []),
    'updateSettings' : IDL.Func([Settings], [], []),
    'updateTrip' : IDL.Func([IDL.Text, Trip], [Trip], []),
    'updateTruck' : IDL.Func([IDL.Text, Truck], [Truck], []),
  });
};

export const init = ({ IDL }) => { return []; };