/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'pendingOrders' : bigint,
  'trucksOnTrip' : bigint,
  'availableTrucks' : bigint,
  'trucksInMaintenance' : bigint,
  'monthlyExpenses' : number,
  'monthlyIncome' : number,
}
export interface Driver {
  'id' : string,
  'assignedTruckId' : [] | [string],
  'name' : string,
  'isActive' : boolean,
  'licenseNumber' : string,
  'salaryUSD' : number,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface FinanceEntry {
  'id' : string,
  'entryType' : string,
  'relatedTripId' : [] | [string],
  'date' : Time,
  'description' : string,
  'category' : string,
  'amountUSD' : number,
}
export interface MaintenanceRecord {
  'id' : string,
  'kmAtService' : bigint,
  'serviceDate' : Time,
  'truckId' : string,
  'serviceType' : string,
  'mechanicName' : string,
  'costUSD' : number,
}
export interface MonthlyReport {
  'totalIncome' : number,
  'totalExpenses' : number,
  'profit' : number,
}
export interface Notification {
  'id' : string,
  'notificationType' : string,
  'createdAt' : Time,
  'isRead' : boolean,
  'message' : string,
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'cargoType' : string,
  'assignedTruckId' : [] | [string],
  'customerPhone' : string,
  'createdAt' : Time,
  'assignedDriverId' : [] | [string],
  'deliveryLocation' : string,
  'priceUSD' : number,
  'pickupLocation' : string,
}
export interface Settings {
  'motto' : string,
  'language' : string,
  'logoUrl' : [] | [ExternalBlob],
  'companyName' : string,
}
export type Time = bigint;
export interface Trip {
  'id' : string,
  'status' : string,
  'truckId' : string,
  'driverId' : string,
  'destination' : string,
  'cargoType' : string,
  'endDate' : [] | [Time],
  'createdAt' : Time,
  'fuelCostUSD' : number,
  'orderId' : string,
  'distanceKm' : number,
  'startLocation' : string,
  'tripPriceUSD' : number,
  'startDate' : Time,
}
export interface Truck {
  'id' : string,
  'status' : string,
  'model' : string,
  'currentKm' : bigint,
  'assignedDriverId' : [] | [string],
  'plateNumber' : string,
  'lastServiceDate' : Time,
  'capacityTons' : number,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDriver' : ActorMethod<[Driver], undefined>,
  'addFinanceEntry' : ActorMethod<[FinanceEntry], undefined>,
  'addMaintenanceRecord' : ActorMethod<[MaintenanceRecord], undefined>,
  'addNotification' : ActorMethod<[Notification], undefined>,
  'addOrder' : ActorMethod<[Order], undefined>,
  'addTrip' : ActorMethod<[Trip], undefined>,
  'addTruck' : ActorMethod<[Truck], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDriver' : ActorMethod<[string], undefined>,
  'deleteFinanceEntry' : ActorMethod<[string], undefined>,
  'deleteMaintenanceRecord' : ActorMethod<[string], undefined>,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'deleteTrip' : ActorMethod<[string], undefined>,
  'deleteTruck' : ActorMethod<[string], undefined>,
  'getAnnualReport' : ActorMethod<[bigint], MonthlyReport>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDriver' : ActorMethod<[string], Driver>,
  'getFinanceEntry' : ActorMethod<[string], FinanceEntry>,
  'getMaintenanceRecord' : ActorMethod<[string], MaintenanceRecord>,
  'getMonthlyReport' : ActorMethod<[bigint, bigint], MonthlyReport>,
  'getNotification' : ActorMethod<[string], Notification>,
  'getOrder' : ActorMethod<[string], Order>,
  'getSettings' : ActorMethod<[], Settings>,
  'getTrip' : ActorMethod<[string], Trip>,
  'getTruck' : ActorMethod<[string], Truck>,
  'getTrucksNeedingMaintenance' : ActorMethod<[], Array<Truck>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDrivers' : ActorMethod<[], Array<Driver>>,
  'listFinanceEntries' : ActorMethod<[], Array<FinanceEntry>>,
  'listMaintenanceByTruck' : ActorMethod<[string], Array<MaintenanceRecord>>,
  'listMaintenanceRecords' : ActorMethod<[], Array<MaintenanceRecord>>,
  'listNotifications' : ActorMethod<[], Array<Notification>>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listTrips' : ActorMethod<[], Array<Trip>>,
  'listTrucks' : ActorMethod<[], Array<Truck>>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDriver' : ActorMethod<[string, Driver], Driver>,
  'updateFinanceEntry' : ActorMethod<[string, FinanceEntry], FinanceEntry>,
  'updateMaintenanceRecord' : ActorMethod<
    [string, MaintenanceRecord],
    MaintenanceRecord
  >,
  'updateOrder' : ActorMethod<[string, Order], Order>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
  'updateTrip' : ActorMethod<[string, Trip], Trip>,
  'updateTruck' : ActorMethod<[string, Truck], Truck>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];