/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MonthlyReport {
    totalIncome: number;
    totalExpenses: number;
    profit: number;
}
export interface Trip {
    id: string;
    status: string;
    truckId: string;
    driverId: string;
    destination: string;
    cargoType: string;
    endDate?: Time;
    createdAt: Time;
    fuelCostUSD: number;
    orderId: string;
    distanceKm: number;
    startLocation: string;
    tripPriceUSD: number;
    startDate: Time;
}
export type Time = bigint;
export interface Driver {
    id: string;
    assignedTruckId?: string;
    name: string;
    isActive: boolean;
    licenseNumber: string;
    salaryUSD: number;
    phone: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MaintenanceRecord {
    id: string;
    kmAtService: bigint;
    serviceDate: Time;
    truckId: string;
    serviceType: string;
    mechanicName: string;
    costUSD: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Order {
    id: string;
    customerName: string;
    status: string;
    cargoType: string;
    assignedTruckId?: string;
    customerPhone: string;
    createdAt: Time;
    assignedDriverId?: string;
    deliveryLocation: string;
    priceUSD: number;
    pickupLocation: string;
}
export interface DashboardStats {
    pendingOrders: bigint;
    trucksOnTrip: bigint;
    availableTrucks: bigint;
    trucksInMaintenance: bigint;
    monthlyExpenses: number;
    monthlyIncome: number;
}
export interface Settings {
    motto: string;
    language: string;
    logoUrl?: ExternalBlob;
    companyName: string;
}
export interface Truck {
    id: string;
    status: string;
    model: string;
    currentKm: bigint;
    assignedDriverId?: string;
    plateNumber: string;
    lastServiceDate: Time;
    capacityTons: number;
}
export interface FinanceEntry {
    id: string;
    entryType: string;
    relatedTripId?: string;
    date: Time;
    description: string;
    category: string;
    amountUSD: number;
}
export interface Notification {
    id: string;
    notificationType: string;
    createdAt: Time;
    isRead: boolean;
    message: string;
}
export interface UserProfile {
    name: string;
    role: string;
    phone?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDriver(driver: Driver): Promise<void>;
    addFinanceEntry(entry: FinanceEntry): Promise<void>;
    addMaintenanceRecord(record: MaintenanceRecord): Promise<void>;
    addNotification(notification: Notification): Promise<void>;
    addOrder(order: Order): Promise<void>;
    addTrip(trip: Trip): Promise<void>;
    addTruck(truck: Truck): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteDriver(id: string): Promise<void>;
    deleteFinanceEntry(id: string): Promise<void>;
    deleteMaintenanceRecord(id: string): Promise<void>;
    deleteOrder(id: string): Promise<void>;
    deleteTrip(id: string): Promise<void>;
    deleteTruck(id: string): Promise<void>;
    getAnnualReport(year: bigint): Promise<MonthlyReport>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getDriver(id: string): Promise<Driver>;
    getFinanceEntry(id: string): Promise<FinanceEntry>;
    getMaintenanceRecord(id: string): Promise<MaintenanceRecord>;
    getMonthlyReport(month: bigint, year: bigint): Promise<MonthlyReport>;
    getNotification(id: string): Promise<Notification>;
    getOrder(id: string): Promise<Order>;
    getSettings(): Promise<Settings>;
    getTrip(id: string): Promise<Trip>;
    getTruck(id: string): Promise<Truck>;
    getTrucksNeedingMaintenance(): Promise<Array<Truck>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listDrivers(): Promise<Array<Driver>>;
    listFinanceEntries(): Promise<Array<FinanceEntry>>;
    listMaintenanceByTruck(truckId: string): Promise<Array<MaintenanceRecord>>;
    listMaintenanceRecords(): Promise<Array<MaintenanceRecord>>;
    listNotifications(): Promise<Array<Notification>>;
    listOrders(): Promise<Array<Order>>;
    listTrips(): Promise<Array<Trip>>;
    listTrucks(): Promise<Array<Truck>>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationRead(notificationId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateDriver(id: string, updatedDriver: Driver): Promise<Driver>;
    updateFinanceEntry(id: string, updatedEntry: FinanceEntry): Promise<FinanceEntry>;
    updateMaintenanceRecord(id: string, updatedRecord: MaintenanceRecord): Promise<MaintenanceRecord>;
    updateOrder(id: string, updatedOrder: Order): Promise<Order>;
    updateSettings(newSettings: Settings): Promise<void>;
    updateTrip(id: string, updatedTrip: Trip): Promise<Trip>;
    updateTruck(id: string, updatedTruck: Truck): Promise<Truck>;
}
import type { Driver as _Driver, ExternalBlob as _ExternalBlob, FinanceEntry as _FinanceEntry, Order as _Order, Settings as _Settings, Time as _Time, Trip as _Trip, Truck as _Truck, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDriver(arg0: Driver): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDriver(to_candid_Driver_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDriver(to_candid_Driver_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addFinanceEntry(arg0: FinanceEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFinanceEntry(to_candid_FinanceEntry_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFinanceEntry(to_candid_FinanceEntry_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMaintenanceRecord(arg0: MaintenanceRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaintenanceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaintenanceRecord(arg0);
            return result;
        }
    }
    async addNotification(arg0: Notification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0);
            return result;
        }
    }
    async addOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrder(to_candid_Order_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrder(to_candid_Order_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTrip(arg0: Trip): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrip(to_candid_Trip_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrip(to_candid_Trip_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTruck(arg0: Truck): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTruck(to_candid_Truck_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTruck(to_candid_Truck_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteDriver(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDriver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDriver(arg0);
            return result;
        }
    }
    async deleteFinanceEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFinanceEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFinanceEntry(arg0);
            return result;
        }
    }
    async deleteMaintenanceRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaintenanceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaintenanceRecord(arg0);
            return result;
        }
    }
    async deleteOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async deleteTrip(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrip(arg0);
            return result;
        }
    }
    async deleteTruck(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTruck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTruck(arg0);
            return result;
        }
    }
    async getAnnualReport(arg0: bigint): Promise<MonthlyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnualReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnualReport(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDriver(arg0: string): Promise<Driver> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriver(arg0);
                return from_candid_Driver_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriver(arg0);
            return from_candid_Driver_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinanceEntry(arg0: string): Promise<FinanceEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinanceEntry(arg0);
                return from_candid_FinanceEntry_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinanceEntry(arg0);
            return from_candid_FinanceEntry_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaintenanceRecord(arg0: string): Promise<MaintenanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenanceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenanceRecord(arg0);
            return result;
        }
    }
    async getMonthlyReport(arg0: bigint, arg1: bigint): Promise<MonthlyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyReport(arg0, arg1);
            return result;
        }
    }
    async getNotification(arg0: string): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotification(arg0);
            return result;
        }
    }
    async getOrder(arg0: string): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_Order_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_Order_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_Settings_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_Settings_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrip(arg0: string): Promise<Trip> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrip(arg0);
                return from_candid_Trip_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrip(arg0);
            return from_candid_Trip_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTruck(arg0: string): Promise<Truck> {
        if (this.processError) {
            try {
                const result = await this.actor.getTruck(arg0);
                return from_candid_Truck_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTruck(arg0);
            return from_candid_Truck_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrucksNeedingMaintenance(): Promise<Array<Truck>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrucksNeedingMaintenance();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrucksNeedingMaintenance();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listDrivers(): Promise<Array<Driver>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDrivers();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDrivers();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFinanceEntries(): Promise<Array<FinanceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFinanceEntries();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFinanceEntries();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMaintenanceByTruck(arg0: string): Promise<Array<MaintenanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMaintenanceByTruck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMaintenanceByTruck(arg0);
            return result;
        }
    }
    async listMaintenanceRecords(): Promise<Array<MaintenanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMaintenanceRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMaintenanceRecords();
            return result;
        }
    }
    async listNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotifications();
            return result;
        }
    }
    async listOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrips();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrips();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTrucks(): Promise<Array<Truck>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrucks();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrucks();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDriver(arg0: string, arg1: Driver): Promise<Driver> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDriver(arg0, to_candid_Driver_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Driver_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDriver(arg0, to_candid_Driver_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Driver_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFinanceEntry(arg0: string, arg1: FinanceEntry): Promise<FinanceEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFinanceEntry(arg0, to_candid_FinanceEntry_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_FinanceEntry_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFinanceEntry(arg0, to_candid_FinanceEntry_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_FinanceEntry_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMaintenanceRecord(arg0: string, arg1: MaintenanceRecord): Promise<MaintenanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaintenanceRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaintenanceRecord(arg0, arg1);
            return result;
        }
    }
    async updateOrder(arg0: string, arg1: Order): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(arg0, to_candid_Order_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Order_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(arg0, to_candid_Order_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Order_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(await to_candid_Settings_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(await to_candid_Settings_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTrip(arg0: string, arg1: Trip): Promise<Trip> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrip(arg0, to_candid_Trip_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Trip_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrip(arg0, to_candid_Trip_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Trip_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTruck(arg0: string, arg1: Truck): Promise<Truck> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTruck(arg0, to_candid_Truck_n16(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Truck_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTruck(arg0, to_candid_Truck_n16(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Truck_n39(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Driver_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Driver): Driver {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FinanceEntry_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinanceEntry): FinanceEntry {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Settings_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Settings): Promise<Settings> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Truck_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Truck): Truck {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    phone: [] | [string];
}): {
    name: string;
    role: string;
    phone?: string;
} {
    return {
        name: value.name,
        role: value.role,
        phone: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    assignedTruckId: [] | [string];
    name: string;
    isActive: boolean;
    licenseNumber: string;
    salaryUSD: number;
    phone: string;
}): {
    id: string;
    assignedTruckId?: string;
    name: string;
    isActive: boolean;
    licenseNumber: string;
    salaryUSD: number;
    phone: string;
} {
    return {
        id: value.id,
        assignedTruckId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.assignedTruckId)),
        name: value.name,
        isActive: value.isActive,
        licenseNumber: value.licenseNumber,
        salaryUSD: value.salaryUSD,
        phone: value.phone
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    entryType: string;
    relatedTripId: [] | [string];
    date: _Time;
    description: string;
    category: string;
    amountUSD: number;
}): {
    id: string;
    entryType: string;
    relatedTripId?: string;
    date: Time;
    description: string;
    category: string;
    amountUSD: number;
} {
    return {
        id: value.id,
        entryType: value.entryType,
        relatedTripId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.relatedTripId)),
        date: value.date,
        description: value.description,
        category: value.category,
        amountUSD: value.amountUSD
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: string;
    cargoType: string;
    assignedTruckId: [] | [string];
    customerPhone: string;
    createdAt: _Time;
    assignedDriverId: [] | [string];
    deliveryLocation: string;
    priceUSD: number;
    pickupLocation: string;
}): {
    id: string;
    customerName: string;
    status: string;
    cargoType: string;
    assignedTruckId?: string;
    customerPhone: string;
    createdAt: Time;
    assignedDriverId?: string;
    deliveryLocation: string;
    priceUSD: number;
    pickupLocation: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: value.status,
        cargoType: value.cargoType,
        assignedTruckId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.assignedTruckId)),
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        assignedDriverId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.assignedDriverId)),
        deliveryLocation: value.deliveryLocation,
        priceUSD: value.priceUSD,
        pickupLocation: value.pickupLocation
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    motto: string;
    language: string;
    logoUrl: [] | [_ExternalBlob];
    companyName: string;
}): Promise<{
    motto: string;
    language: string;
    logoUrl?: ExternalBlob;
    companyName: string;
}> {
    return {
        motto: value.motto,
        language: value.language,
        logoUrl: record_opt_to_undefined(await from_candid_opt_n34(_uploadFile, _downloadFile, value.logoUrl)),
        companyName: value.companyName
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    truckId: string;
    driverId: string;
    destination: string;
    cargoType: string;
    endDate: [] | [_Time];
    createdAt: _Time;
    fuelCostUSD: number;
    orderId: string;
    distanceKm: number;
    startLocation: string;
    tripPriceUSD: number;
    startDate: _Time;
}): {
    id: string;
    status: string;
    truckId: string;
    driverId: string;
    destination: string;
    cargoType: string;
    endDate?: Time;
    createdAt: Time;
    fuelCostUSD: number;
    orderId: string;
    distanceKm: number;
    startLocation: string;
    tripPriceUSD: number;
    startDate: Time;
} {
    return {
        id: value.id,
        status: value.status,
        truckId: value.truckId,
        driverId: value.driverId,
        destination: value.destination,
        cargoType: value.cargoType,
        endDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.endDate)),
        createdAt: value.createdAt,
        fuelCostUSD: value.fuelCostUSD,
        orderId: value.orderId,
        distanceKm: value.distanceKm,
        startLocation: value.startLocation,
        tripPriceUSD: value.tripPriceUSD,
        startDate: value.startDate
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    model: string;
    currentKm: bigint;
    assignedDriverId: [] | [string];
    plateNumber: string;
    lastServiceDate: _Time;
    capacityTons: number;
}): {
    id: string;
    status: string;
    model: string;
    currentKm: bigint;
    assignedDriverId?: string;
    plateNumber: string;
    lastServiceDate: Time;
    capacityTons: number;
} {
    return {
        id: value.id,
        status: value.status,
        model: value.model,
        currentKm: value.currentKm,
        assignedDriverId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.assignedDriverId)),
        plateNumber: value.plateNumber,
        lastServiceDate: value.lastServiceDate,
        capacityTons: value.capacityTons
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Truck>): Array<Truck> {
    return value.map((x)=>from_candid_Truck_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Driver>): Array<Driver> {
    return value.map((x)=>from_candid_Driver_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FinanceEntry>): Array<FinanceEntry> {
    return value.map((x)=>from_candid_FinanceEntry_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n36(_uploadFile, _downloadFile, x));
}
function to_candid_Driver_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Driver): _Driver {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FinanceEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinanceEntry): _FinanceEntry {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Order_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_Settings_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Settings): Promise<_Settings> {
    return await to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_Trip_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trip): _Trip {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Truck_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Truck): _Truck {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    entryType: string;
    relatedTripId?: string;
    date: Time;
    description: string;
    category: string;
    amountUSD: number;
}): {
    id: string;
    entryType: string;
    relatedTripId: [] | [string];
    date: _Time;
    description: string;
    category: string;
    amountUSD: number;
} {
    return {
        id: value.id,
        entryType: value.entryType,
        relatedTripId: value.relatedTripId ? candid_some(value.relatedTripId) : candid_none(),
        date: value.date,
        description: value.description,
        category: value.category,
        amountUSD: value.amountUSD
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: string;
    cargoType: string;
    assignedTruckId?: string;
    customerPhone: string;
    createdAt: Time;
    assignedDriverId?: string;
    deliveryLocation: string;
    priceUSD: number;
    pickupLocation: string;
}): {
    id: string;
    customerName: string;
    status: string;
    cargoType: string;
    assignedTruckId: [] | [string];
    customerPhone: string;
    createdAt: _Time;
    assignedDriverId: [] | [string];
    deliveryLocation: string;
    priceUSD: number;
    pickupLocation: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: value.status,
        cargoType: value.cargoType,
        assignedTruckId: value.assignedTruckId ? candid_some(value.assignedTruckId) : candid_none(),
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        assignedDriverId: value.assignedDriverId ? candid_some(value.assignedDriverId) : candid_none(),
        deliveryLocation: value.deliveryLocation,
        priceUSD: value.priceUSD,
        pickupLocation: value.pickupLocation
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    truckId: string;
    driverId: string;
    destination: string;
    cargoType: string;
    endDate?: Time;
    createdAt: Time;
    fuelCostUSD: number;
    orderId: string;
    distanceKm: number;
    startLocation: string;
    tripPriceUSD: number;
    startDate: Time;
}): {
    id: string;
    status: string;
    truckId: string;
    driverId: string;
    destination: string;
    cargoType: string;
    endDate: [] | [_Time];
    createdAt: _Time;
    fuelCostUSD: number;
    orderId: string;
    distanceKm: number;
    startLocation: string;
    tripPriceUSD: number;
    startDate: _Time;
} {
    return {
        id: value.id,
        status: value.status,
        truckId: value.truckId,
        driverId: value.driverId,
        destination: value.destination,
        cargoType: value.cargoType,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        createdAt: value.createdAt,
        fuelCostUSD: value.fuelCostUSD,
        orderId: value.orderId,
        distanceKm: value.distanceKm,
        startLocation: value.startLocation,
        tripPriceUSD: value.tripPriceUSD,
        startDate: value.startDate
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    model: string;
    currentKm: bigint;
    assignedDriverId?: string;
    plateNumber: string;
    lastServiceDate: Time;
    capacityTons: number;
}): {
    id: string;
    status: string;
    model: string;
    currentKm: bigint;
    assignedDriverId: [] | [string];
    plateNumber: string;
    lastServiceDate: _Time;
    capacityTons: number;
} {
    return {
        id: value.id,
        status: value.status,
        model: value.model,
        currentKm: value.currentKm,
        assignedDriverId: value.assignedDriverId ? candid_some(value.assignedDriverId) : candid_none(),
        plateNumber: value.plateNumber,
        lastServiceDate: value.lastServiceDate,
        capacityTons: value.capacityTons
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    phone?: string;
}): {
    name: string;
    role: string;
    phone: [] | [string];
} {
    return {
        name: value.name,
        role: value.role,
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
async function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    motto: string;
    language: string;
    logoUrl?: ExternalBlob;
    companyName: string;
}): Promise<{
    motto: string;
    language: string;
    logoUrl: [] | [_ExternalBlob];
    companyName: string;
}> {
    return {
        motto: value.motto,
        language: value.language,
        logoUrl: value.logoUrl ? candid_some(await to_candid_ExternalBlob_n50(_uploadFile, _downloadFile, value.logoUrl)) : candid_none(),
        companyName: value.companyName
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    assignedTruckId?: string;
    name: string;
    isActive: boolean;
    licenseNumber: string;
    salaryUSD: number;
    phone: string;
}): {
    id: string;
    assignedTruckId: [] | [string];
    name: string;
    isActive: boolean;
    licenseNumber: string;
    salaryUSD: number;
    phone: string;
} {
    return {
        id: value.id,
        assignedTruckId: value.assignedTruckId ? candid_some(value.assignedTruckId) : candid_none(),
        name: value.name,
        isActive: value.isActive,
        licenseNumber: value.licenseNumber,
        salaryUSD: value.salaryUSD,
        phone: value.phone
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
